services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  vault:
    image: vault:1.13.0
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    command: server -dev -dev-root-token-id=root

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-mongo
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      VAULT_TOKEN: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: ${VAULT_ADDR}

    depends_on:
      - mongo
      - vault
    ports:
      - "8080:8080"

volumes:
  mongo_data:
