server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

vault:
  uri: ${VAULT_ADDR}
  token: ${VAULT_DEV_ROOT_TOKEN_ID}
  config:
    lifecycle:
      enabled: true  # Active le cycle de vie de Vault pour renouveler le token automatiquement
    ssl:
      enabled: false  # Pour le mode dev; en production, active SSL si nécessaire
  kv:
    enabled: true  # Active la lecture de secrets dans Vault
