server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

vault:
  uri: ${VAULT_ADDR}
  token: ${VAULT_DEV_ROOT_TOKEN_ID}
  config:
    lifecycle:
      enabled: true
    ssl:
      enabled: false
  kv:
    enabled: true
